---
title: "Dollar Data Science"
output: 
  flexdashboard::flex_dashboard:
    theme: simplex
    orientation: rows
    logo: logo_simple.png
    favicon: logo_simple.png
    

params:
  player: Steph
  games: 5
  
---


```{r setup, include=FALSE, echo = FALSE}

library(tidyverse)
library(nbastatR)
library(stringr)
library(caret)
library(ggplot2)
library(ggpubr)
library(knitr)
library(data.table)
library(broom)
library(grid)
library(gridExtra)
library(grDevices)
library(reactablefmtr)
library(formattable)
library(markdown)
library(magick)
library(highcharter)
library(extrafont)
library(cowplot)
library(fmsb)
library(shiny)
library(fontawesome)
library(dplyr)
library(flexdashboard)
library(shinydashboard)
library(ggbreak)
library(plotly)
library(bslib)
library(rsconnect)





Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

gamedata <- game_logs(seasons = 2024, result_types = "team", season_types = c("Regular Season","Playoffs"))
gamedata_current <- game_logs(seasons = 2025, result_types = "team", season_types = c("Regular Season"))

current_season <- "2024-25"
last_season <- "2023-24"

gamedata <- bind_rows(gamedata,gamedata_current)
                              
                            
playerdata <- game_logs(seasons = 2024, result_types = "player", season_types = c("Regular Season","Playoffs"))
playerdata_current <- game_logs(seasons = 2025, result_types = "player", season_types = c("Regular Season"))

playerdata <- bind_rows(playerdata,playerdata_current)

season <- playerdata %>% pull(slugSeason)

player_test <- c("LeBron James","Stephen Curry")

player_id <- function(x){
  
  playerdata %>% filter(str_detect(namePlayer,x)) %>% 
  select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,
         plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond) %>% group_by(idPlayer) %>% summarize(n = n()) %>% select(idPlayer)
  
}

player_id <- lapply(player_test,player_id)

player_id <- bind_rows(player_id) %>% pull(idPlayer)


gameids<- playerdata %>% filter(idPlayer %in% player_id)%>% group_by(idGame) %>% summarize(n = n()) %>% pull(idGame)





```

```{r variables, echo = FALSE }

player_name <- playerdata %>% filter(idPlayer %in% player_id) %>% 
  select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,
         plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond) %>% pull(namePlayer)






  
  
```



Summary
=======================================================================


<center> <h2>Season Stats</h2></center>

```{r Season Stats, echo = FALSE, warning = FALSE, message = FALSE, fig.align='left', fig.width = 9, error = TRUE}



frame_test <- function(x){
  
player_name <- playerdata %>% filter(idPlayer == x) %>% 
  select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,
         plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond) %>% pull(namePlayer)  
  


pts_per_attempt <- as.data.frame(playerdata %>% filter(slugSeason == current_season,typeSeason == "Regular Season") %>% group_by(namePlayer,idPlayer,slugTeam) %>% summarize(n = n(), pts = sum(pts), fga = sum(fga), min = sum(minutes))  %>% mutate(points_per_attempt = (pts/fga))) %>% mutate(rank = order(order(points_per_attempt, decreasing = T))) %>% arrange(desc(points_per_attempt))


pts_per_attempt_avg <- pts_per_attempt %>% filter(idPlayer == x) %>% pull(points_per_attempt)
pts_per_attempt_n <- pts_per_attempt %>% filter(idPlayer == x) %>% pull(n)

player_data <- playerdata %>% filter(idPlayer == x) %>% select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,
         plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond, slugSeason,typeSeason,ftm)

player_data_expanded <- playerdata  %>% select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond, slugSeason,typeSeason) %>% group_by(dateGame,locationGame,namePlayer, idPlayer, typeSeason) %>% summarize(n = n()) 

play_play_player <- play_play %>% filter(idPlayerNBA1 == x, !is.na(slugScore))
play_play_player_assists <- play_play %>% filter(idPlayerNBA2 == x, str_detect(descriptionPlayHome,"AST") | str_detect(descriptionPlayVisitor,"AST"))
play_play_player_rebounds <- play_play %>% filter(is.na(slugScore),idPlayerNBA1 == x, str_detect(descriptionPlayHome,"REBOUND") | str_detect(descriptionPlayVisitor,"REBOUND"))

play_play_all <- play_play %>% filter(!is.na(slugScore))
play_play_all_assists <- play_play %>% filter( str_detect(descriptionPlayHome,"AST") | str_detect(descriptionPlayVisitor,"AST"))
play_play_all_rebounds <- play_play %>% filter(is.na(slugScore), str_detect(descriptionPlayHome,"REBOUND") | str_detect(descriptionPlayVisitor,"REBOUND"))

play_play_makes <- play_play_player %>% select(idGame,numberPeriod, descriptionPlayHome,descriptionPlayNeutral,descriptionPlayVisitor, namePlayer1,slugScore,scoreHome,scoreAway,slugTeamPlayer1) %>% rename(slugTeam = slugTeamPlayer1) %>% mutate(description = ifelse(is.na(descriptionPlayHome),ifelse(is.na(descriptionPlayNeutral),descriptionPlayVisitor,descriptionPlayNeutral),descriptionPlayHome)) %>% mutate(free_throw_flag = str_detect(description,"Free Throw"), three_point_flag = str_detect(description,"3PT")) %>% mutate(two_point_flag = ifelse(free_throw_flag == FALSE & three_point_flag == FALSE, TRUE,FALSE)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,locationGame,slugTeam,slugSeason) %>% summarize(n = n()), by = c("idGame","slugTeam")) %>% mutate(pts = ifelse(free_throw_flag == TRUE,1,ifelse(two_point_flag== TRUE,2,3)),score_type = ifelse(free_throw_flag == TRUE,"Free Throw",ifelse(two_point_flag== TRUE,"2 pt","3 pt")))

play_play_makes_expanded <- play_play_player %>% select(idGame,numberPeriod, descriptionPlayHome,descriptionPlayNeutral,descriptionPlayVisitor, namePlayer1, idPlayerNBA1, slugScore,scoreHome,scoreAway, slugTeamPlayer1) %>% rename(slugTeam = slugTeamPlayer1) %>% mutate(description = ifelse(is.na(descriptionPlayHome),ifelse(is.na(descriptionPlayNeutral),descriptionPlayVisitor,descriptionPlayNeutral),descriptionPlayHome)) %>% mutate(free_throw_flag = str_detect(description,"Free Throw"), three_point_flag = str_detect(description,"3PT")) %>% mutate(two_point_flag = ifelse(free_throw_flag == FALSE & three_point_flag == FALSE, TRUE,FALSE)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,locationGame, slugTeam,slugSeason) %>% summarize(n = n()), by = c("idGame","slugTeam")) %>% mutate(pts = ifelse(free_throw_flag == TRUE,1,ifelse(two_point_flag== TRUE,2,3)),score_type = ifelse(free_throw_flag == TRUE,"Free Throw",ifelse(two_point_flag== TRUE,"2 pt","3 pt"))) %>% group_by(dateGame,namePlayer1,idPlayerNBA1) %>% summarize(pts = sum(pts))

firstq_makes <- player_data %>% group_by(dateGame,locationGame,typeSeason,slugOpponent,slugSeason) %>% summarize(n = n()) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(dateGame) %>% summarize(pts = sum(pts)), by = "dateGame") %>% mutate(pts = replace_na(pts,0))

firstq_makes_expanded <- player_data_expanded %>% left_join(play_play_makes_expanded %>% rename(idPlayer = idPlayerNBA1), by = c("dateGame","idPlayer")) %>% mutate(pts = replace_na(pts,0))

play_play_assists <- play_play_player_assists %>% select(idGame,numberPeriod,descriptionPlayHome,descriptionPlayVisitor, namePlayer1,namePlayer2,slugTeamPlayer1) %>% rename(slugTeam = slugTeamPlayer1) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,locationGame,slugTeam,slugSeason) %>% summarize(n = n()), by = c("idGame","slugTeam"))

firstq_assists <- player_data %>% group_by(dateGame,locationGame,typeSeason,slugOpponent,slugSeason) %>% summarize(n = n()) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(dateGame,typeSeason,locationGame) %>% summarize(assists = n()), by = "dateGame") %>% mutate(assists = replace_na(assists,0)) %>% rename(locationGame = locationGame.x, typeSeason = typeSeason.x)

play_play_rebounds <- play_play_player_rebounds %>% select(idGame,numberPeriod,descriptionPlayHome,descriptionPlayVisitor, namePlayer1,slugTeamPlayer1) %>% rename(slugTeam = slugTeamPlayer1) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,locationGame,slugTeam,slugSeason) %>% summarize(n = n()), by = c("idGame","slugTeam")) 

firstq_rebounds <- player_data %>% group_by(dateGame,locationGame,typeSeason,slugOpponent,slugSeason) %>% summarize(n = n()) %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(dateGame,typeSeason,locationGame) %>% summarize(rebounds = n()), by = "dateGame") %>% mutate(rebounds = replace_na(rebounds,0)) %>% rename(locationGame = locationGame.x, typeSeason = typeSeason.x)



season <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,slugSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,slugSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Regular Season",slugSeason == current_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season))*0)), nrow = 1, ncol=ncol(season)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_frame <- if(nrow(season)==0){error}else{season}


season_last <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,slugSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason,slugSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Regular Season",slugSeason == last_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_last)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season))*0)), nrow = 1, ncol=ncol(season_last)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_last_frame <- if(nrow(season_last)==0){error}else{season_last}



b2b <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Regular Season", isB2BSecond == TRUE,slugSeason == current_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(b2b)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(b2b))*0)), nrow = 1, ncol=ncol(b2b)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
b2b_frame <- if(nrow(b2b)==0){error}else{b2b}



season_last10 <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% arrange(desc(dateGame)) %>% head(10) %>% group_by(namePlayer) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_last10)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_last10))*0)), nrow = 1, ncol=ncol(season_last10)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_last10_frame <- if(nrow(season_last10)==0){error}else{season_last10}



season_last5 <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% arrange(desc(dateGame)) %>% head(5) %>% group_by(namePlayer) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_last5)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_last5))*0)), nrow = 1, ncol=ncol(season_last5)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_last5_frame <- if(nrow(season_last5)==0){error}else{season_last5}



season_home <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(locationGame == "H", typeSeason == "Regular Season",slugSeason == current_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_home)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_home))*0)), nrow = 1, ncol=ncol(season_home)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_home_frame <- if(nrow(season_home)==0){error}else{season_home}



season_away <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(locationGame == "A", typeSeason == "Regular Season",slugSeason == current_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_away)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_away))*0)), nrow = 1, ncol=ncol(season_away)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_away_frame <- if(nrow(season_away)==0){error}else{season_away}



season_opponent <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(slugOpponent == next_opponent, typeSeason == "Regular Season",slugSeason == current_season) %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(season_opponent)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_opponent))*0)), nrow = 1, ncol=ncol(season_opponent)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
season_opponent_frame <- if(nrow(season_opponent)==0){error}else{season_opponent}





playoff <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Playoffs") %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(playoff)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_opponent))*0)), nrow = 1, ncol=ncol(playoff)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
playoff_frame <- if(nrow(playoff)==0){error}else{playoff}


playoff_away <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata  %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Playoffs", locationGame == "A") %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(playoff_away)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_opponent))*0)), nrow = 1, ncol=ncol(playoff_away)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
playoff_away_frame <- if(nrow(playoff_away)==0){error}else{playoff_away}


playoff_home <- player_data %>% left_join(play_play_rebounds %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqrebounds = n()), by = "idGame") %>% mutate(firstqrebounds = replace_na(firstqrebounds,0)) %>% left_join(play_play_assists %>% filter(numberPeriod == 1) %>% group_by(idGame) %>% summarize(firstqassists = n()), by = "idGame") %>% mutate(firstqassists = replace_na(firstqassists,0)) %>% left_join(play_play_makes %>% filter(numberPeriod == 1) %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n(),firstqpoints = sum(pts)) %>% left_join(gamedata %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame) %>% summarize(firstqpoints = sum(firstqpoints)), by = "idGame") %>% mutate(firstqpoints = replace_na(firstqpoints,0)) %>% left_join(play_play_makes %>% group_by(idGame,namePlayer1,slugScore,scoreHome,scoreAway,score_type) %>% summarize(n = n()) %>% mutate(first = ifelse((scoreHome >0 & scoreAway == 0) | (scoreAway > 0 & scoreHome == 0),1,0))%>% left_join(gamedata  %>% group_by(idGame,dateGame,typeSeason) %>% summarize(n = n()), by = "idGame") %>% group_by(idGame,first) %>% summarize(n = n()) %>% filter(first == 1), by = "idGame") %>% mutate(first = replace_na((first),0)) %>% filter(typeSeason == "Playoffs", locationGame == "H") %>% group_by(namePlayer,slugSeason) %>% summarize(n = n(), total_pts = sum(pts), total_reb = sum(treb), total_ast = sum(ast), total_stl = sum(stl), total_blk = sum(blk), total_fgm = sum(fgm), total_fga = sum(fga), total_fg3m = sum(fg3m), total_minutes = sum(minutes), total_tov = sum(tov), total_first = sum(first), totalfqpts = sum(firstqpoints), totalfqast = sum(firstqassists), totalfqtreb = sum(firstqrebounds), totalftm = sum(ftm), total_fg3a = sum(fg3a)) %>% mutate(ppg = round(total_pts/n,1), rpg = round(total_reb/n,1), apg = round(total_ast/n,1), spg = round(total_stl/n,1), bpg = round(total_blk/n,1), fg_percentage = round((total_fgm/total_fga)*100,1), fg3_percentage = round((total_fg3m/total_fg3a)*100,1), min = round(total_minutes/n,1),threepg = round(total_fg3m/n,1),threeattempt = round(total_fg3a/n,1), tovpg = round(total_tov/n,1), pts_ast = round((total_pts+total_ast)/n,1), pts_reb_ast = round((total_reb+total_pts+total_ast)/n,1), pts_reb = round((total_pts+total_reb)/n,1), ast_reb = round((total_ast+total_reb)/n,1),firstqppg = round(totalfqpts/n,1), firstqapg = round(totalfqast/n,1), firstqrpg = round(totalfqtreb/n,1), pts_per_attempt = round(total_pts/total_fga,2), ftmpg = round(totalftm/n,1),stl_blk = round((total_blk+total_stl)/n,1), fgapg = round(total_fga/n,1),fgmpg = round(total_fgm/n,1) ) %>% ungroup() %>% select(namePlayer,n,min,ppg,rpg,apg,spg,bpg,threepg,threeattempt,fg_percentage,fgmpg,fgapg,fg3_percentage,ftmpg,tovpg, pts_reb_ast, pts_ast,pts_reb,ast_reb,stl_blk, total_first,firstqppg,firstqapg,firstqrpg, pts_per_attempt) %>%rename(GP = n,`FG` = fg_percentage, `FG_3P` = fg3_percentage)

names <- colnames(playoff_home)
error <- as.data.frame(matrix(c(player_name[1], as.integer(seq(1:ncol(season_opponent))*0)), nrow = 1, ncol=ncol(playoff_home)))
colnames(error) <- names
error[, -1] <- sapply(error[, -1], as.numeric)
playoff_home_frame <- if(nrow(playoff_home)==0){error}else{playoff_home}

Type <- c("2024/25 Regular Season","2023/24 Regular Season","Last 10 GP","Last 5 GP","2024/25 Regular Season Home","2024/25 Regular Season Away",paste("Against",next_opponent,"Regular Season"),"Second Night of Back of Back")
combined <- bind_rows(season_frame,season_last_frame,season_last10_frame,season_last5_frame,season_home_frame,season_away_frame,season_opponent_frame,b2b_frame)


df <- data.frame(Type,combined)

df2 <- df %>% select(Type,namePlayer,GP,min,ppg,rpg,apg,spg,bpg,tovpg,fgmpg,fgapg,threepg,threeattempt,ftmpg,FG,FG_3P,pts_reb_ast,pts_ast,pts_reb,ast_reb,stl_blk,total_first,firstqppg,firstqapg,firstqrpg,pts_per_attempt) %>% 
  rename(Min = min,
         PPG = ppg,
         RPG = rpg,
         APG = apg,
         SPG = spg,
         BPG = bpg,
         TOV = tovpg,
         FGM = fgmpg,
         FGA = fgapg,
         FG3M = threepg,
         FG3A = threeattempt,
         FTM = ftmpg,
         `FG%` = FG,
         `3FG%` = FG_3P,
         `Pts+Reb+Ast` = pts_reb_ast,
         `Pts+Ast` = pts_ast,
         `Pts+Reb` = pts_reb,
         `Reb+Ast` = ast_reb,
         `Stl+Blk` = stl_blk,
         `First Scorer Count` = total_first,
         `Q1 PPG` = firstqppg,
         `Q1 APG` = firstqapg,
         `Q1 RPG` = firstqrpg,
         `Pts Per Attempt` = pts_per_attempt)

df2 <- replace(df2, is.na(df2),0)

#print.data.frame(df2)

tab1<- formattable(df2,align = "c",list(Min = color_tile("white","gold"),PPG = color_tile("white","gold"),RPG = color_tile("white","gold"),APG = color_tile("white","gold"),SPG = color_tile("white","gold"),BPG = color_tile("white","gold"),TOV = color_tile("white","gold"),FGM = color_tile("white","gold"),FGA = color_tile("white","gold"),FG3M = color_tile("white","gold"),FG3A = color_tile("white","gold"),FTM = color_tile("white","gold"),`FG%` = color_tile("white","gold"),`3FG%`= color_tile("white","gold"), `Pts+Reb+Ast` = color_tile("white","gold"), `Pts+Ast` = color_tile("white","gold"), `Pts+Reb` = color_tile("white","gold"), `Reb+Ast` = color_tile("white","gold"),`Stl+Blk` = color_tile("white","gold"), `First Scorer Count` = color_tile("white","gold"), `Q1 PPG` = color_tile("white","gold"), `Q1 APG` = color_tile("white","gold"), `Q1 RPG` = color_tile("white","gold"), `Pts Per Attempt` = color_tile("white","gold")), caption = "First Scorer Count Includes Free Throws. Second Night of Back to Back represents back to back for the team")

tab1



}

frame_test <- lapply(player_id, frame_test)
frame_test <- bind_rows(frame_test)










```

```{r}




ui <- 
  
  dashboardPage(
  dashboardHeader(title = "Dollar Data Science"),
  dashboardSidebar(
    
    sidebarMenu(
    
      selectInput(inputId = "player",
                label = "Choose Player",
                choices = player_test,
                selected = NULL),
    menuItem("Season Stats",tabName = "stats", icon = icon("dashboard")),
    menuItem("Exploratory Analysis", icon = icon("th"), tabName = "analysis", badgeLabel = "new", badgeColor = "green")
  )),
  
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "stats",
              
    
         fluidPage(
            formattableOutput("table")),

    ),
      tabItem(tabName = "analysis",
              
          
          
          fluidRow(
            column(width = 12,
                   box(
                     title = "Bin Selector",
                     sliderInput("slider","Select # of Bins:",1,10,1)
                   ),
                    box(
                      plotlyOutput("plot2", height = 500)))
            
            
          ),    
    
          fluidPage(
            column(width = 12,
              box(
                plotlyOutput("plot1", height = 500))),
          
            
            

    )            
            
            )
  )
  
))

server <- function(input, output) {
  
  
  output$table<- renderFormattable({
    
    frame_test %>% filter(namePlayer == input$player)
    
  })
  
    output$plot1<- renderPlotly({
      
      metric = "minutes"

    avg <- mean(player_data %>% filter(typeSeason == "Regular Season", slugSeason == current_season) %>% pull(metric))
    avg_lastx <- mean(player_data %>% arrange(desc(dateGame)) %>% head(params$games) %>% pull(metric))
      
     p <- player_data %>% filter(namePlayer == input$player) %>% ggplot(aes(dateGame,.data[[metric]], label = slugOpponent)) +geom_line() + geom_point(aes(color = locationGame, shape = typeSeason)) + geom_smooth(span = 0.6) + labs(x = "Date")  + scale_y_continuous(breaks = seq(0,90,2)) + geom_hline(yintercept = avg) + ggtitle(toupper(paste(input$player,metric,"Per Game")), subtitle = toupper(paste("Current Season Avg:",round(avg,1),"/","Avg Last",params$games,"games:",round(avg_lastx,1)))) + theme_minimal() + scale_x_date(breaks = "1 month", date_labels = "%b") + scale_color_manual(values = c(primary_color,secondary_color)) + scale_shape_manual(values = c(15,16)) + facet_grid(~ slugSeason, scales = "free_x")+ guides(color = guide_legend(title = ""),shape = guide_legend(title = ""))
     
     ggplotly(p) %>% layout(legend = list(orientation = "h", x = 0, y = -0.2), 
                       title = list(text = toupper(paste(input$player,metric,"Per Game",'<br>','<sup>',toupper(paste("Current Season Avg:",round(avg,1),"/","Avg Last",params$games,"games:",round(avg_lastx,1))),'</sup>'))))
    
    
  })
    
    output$plot2<- renderPlotly({
      
      metric = "minutes"

    p <- player_data %>% filter(typeSeason == "Regular Season", slugSeason == current_season, namePlayer == input$player) %>% ggplot(aes(.data[[metric]])) + geom_histogram(bins = input$slider, color = secondary_color, fill = primary_color)+ scale_x_continuous(breaks = seq(0,90,2))+ ggtitle(toupper(paste(params$player,"Regular Season",metric,"histogram"))) + theme_minimal()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p) %>% layout(title = list(text = toupper(paste(input$player,metric,"histogram",'<br>','<sup>',toupper("Current Regular Season"),'</sup>'))))
    
    
  })
  
}

shinyApp(ui, server)


```




