---
title: "Play Play"
author: "Christopher Craig"
date: "`r Sys.Date()`"
output: html_document

params:
  team: GSW

---

```{r setup}

library(tidyverse)
library(nbastatR)
library(dplyr)
library(flexdashboard)
library(parallel)
library(reactable)


Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

gamedata <- game_logs(seasons = 2024, result_types = "team", season_types = c("Regular Season"))

teams <- gamedata %>% group_by(slugTeam) %>% summarize(n = n()) %>% pull(slugTeam)



gameids<- gamedata %>% group_by(idGame) %>% summarize(n = n()) %>% pull(idGame)

numcores <- parallelly::availableCores()

cl <- makeCluster(numcores)

my_function <- function(x) {
  library(tidyverse)
  library(nbastatR)
  
  play_play <- play_by_play_v2(game_ids = x,nest_data = F)
  
}

results <- parLapply(cl,gameids,my_function)
play_play <- bind_rows(results)

stopCluster(cl)




```



```{r loop}

for (team in teams) {
  rmarkdown::render(input = 'C:/Users/CECRAIG/Desktop/Backironanalytics/my-site-test/Play_Play_Output.Rmd',
                    output_file = paste0(team,".html"),
                    output_dir = file.path('C:/Users/CECRAIG/Desktop/Backironanalytics/my-site-test/play'),
                    params = list(team = team))

}


```






