---
title: "Parallel Test"
author: "Christopher Craig"
date: "`r Sys.Date()`"
output: html_document


params:
  team: Warriors
  player: [Luka Doncic,Steph,Tatum,Anthony Edwards,Embiid,Jalen Brunson,Damian Lillard,Nikola Jokic, Kyrie Irving, Devin Booker, Kevin Durant, Jaylen Brown,  
  Jamal Murray, Shai, Chet, Giannis, Trae Young, Jimmy Butler, Bam Adebayo, Ja Morant,Victor Wembanyama,Dejounte Murray]
  games: 5
  
  
---

```{r setup}

library(tidyverse)
library(nbastatR)
library(dplyr)
library(flexdashboard)
library(parallel)


Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

playerdata <- game_logs(seasons = 2024, result_types = "player", season_types = c("Regular Season","Playoffs"))

player_name <- function(x){
  
  playerdata %>% filter(str_detect(namePlayer,x)) %>% 
  select(dateGame, idGame, slugOpponent, idPlayer, namePlayer, fgm,fga,pts,treb,ast,stl,blk,fg3m,fg3a,tov,
         plusminus,minutes,locationGame, countDaysRestPlayer, isB2B, isB2BFirst, isB2BSecond) %>% group_by(namePlayer) %>% summarize(n = n()) %>% pull(namePlayer)
  
}

player_name <- lapply(params$player,player_name)

players <- player_name

players <- unlist(players)

gameids<- playerdata %>% group_by(idGame) %>% summarize(n = n()) %>% pull(idGame)

numcores <- parallelly::availableCores()

cl <- makeCluster(numcores)

my_function <- function(x) {
  library(tidyverse)
  library(nbastatR)
  
  play_play <- play_by_play_v2(game_ids = x,nest_data = F)
  
}

results <- parLapply(cl,gameids,my_function)
play_play <- bind_rows(results)

stopCluster(cl)



```



```{r loop}



for (player in players) {
  rmarkdown::render(input = 'C:/Users/CECRAIG/Desktop/Backironanalytics/my-site-test/ML_Parlay_TBRv5.Rmd',
                    output_file = paste0(player,".html"),
                    output_dir = file.path('C:/Users/CECRAIG/Desktop/Backironanalytics/my-site-test/sheets'),
                    params = list(player = player))

}



```






